src/admin/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using admin.Models;

namespace admin.Controllers
{
    using admin.Service;
    using LinqToExcel;

    [Authorize(Roles = "管理員,總經理,業務主管,業務秘書")]
    public class EmployeeController : Controller
    {
        protected EmpService Service;

        public EmployeeController()
        {
            Service = new EmpService();
        }

        [HttpGet]
        public ActionResult Selector()
        {
            var Data = Service.GetListForSelector(User.Identity.Name);

            return View(Data);
        }

        //
        // GET: /Employee/List
        public ActionResult List(EmployeeListModel page)
        {
            try
            {
                EmployeeListModel model = Service.GetList(User.Identity.Name, page);

                return View(model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(" ", ex.Message);
            }
            return View(page);
        }

        public ActionResult Add()
        {
            EmployeeModel entity = new EmployeeModel();

            return View(entity);
        }

        [HttpPost]
        public ActionResult Import(HttpPostedFileBase f)
        {
            Dictionary<string, object> dErrMsg = new Dictionary<string,object>();

            if (f != null)
            {
                if (System.IO.Path.GetExtension(f.FileName).ToLower().Equals(".xlsx") ||
                    System.IO.Path.GetExtension(f.FileName).ToLower().Equals(".xls")
                    )
                {
                    string strFileName = System.IO.Path.GetFileName(f.FileName);
                    string strAbsFilePath = Server.MapPath("~/App_Data/Temp/" + strFileName);

                    f.SaveAs(strAbsFilePath);

                    Service.ExcelImport(strAbsFilePath, out dErrMsg);
                }
            }
            else
            {
                dErrMsg.Add("file", "無上傳檔案");
            }

            string strRs = dErrMsg.Keys.Count() == 0 ? "OK" : "Error";
            string strErrMsg = dErrMsg.Keys.Count() == 0 ? "" : dErrMsg[dErrMsg.Keys.FirstOrDefault()].ToString();

            return Content("<script type='text/javascript'>parent.excel.onComplete({RS:'" + strRs + "',msg:'" + strErrMsg + "'});</script>");
        }

        [HttpPost]
        public ActionResult Create(EmployeeModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    List<string> liErrMsgs = new List<string>();

                    if (Service.Create(model, out liErrMsgs))
                    {
                        return RedirectToAction("List"); 
                    }

                    ModelState.AddModelError(" ", liErrMsgs.LastOrDefault());
                    
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(" ", ex.Message);
                }
            }
            return View("Add", model);
        }

        public ActionResult Edit(string id)
        {
            EmployeeModel model = Service.Get(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Update(EmployeeModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (Service.Update(model))
                    {
                        return RedirectToAction("List"); 
                    }
                    else
                    {
                        ModelState.AddModelError("", "修改失敗");
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return View("Edit", model);
        }

        public ActionResult Delete(string id)
        {
            try
            {
                if (Service.Delete(id))
                {
                    TempData["delete"] = true;
                }
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(" ", ex.Message);
            }
            return RedirectToAction("List");
        }

        //[{"id":"Mimus polyglottos","label":"Northern Mockingbird","value":"Northern Mockingbird"}]
        //給自動完成用的 action 
        //GET: Employee/SearchByName
        public ActionResult SearchByName(string term)
        {
            //[{"id":"Mimus polyglottos","label":"Northern Mockingbird","value":"Northern Mockingbird"}]

            var Query = Service.GetList(User.Identity.Name,
                new EmployeeListModel() { StartWith = term, Page = 1, PageSize = 10 });

            if (Query.Data != null)
            {
                var o_query = Query.Data.Select(p => new AutocompleteModel()
                {
                    id = p.EmpSN,
                    label = string.Format("{0}({1})", p.Name, p.EmpSN),
                    value = p.EmpSN
                });

                return Json(o_query.ToList(), JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Content(string.Empty);
            }
        }
    }
}

src/admin/Views/Employee/Add.cshtml
@model admin.Models.EmployeeModel

@{
     string _Controller = Request.RequestContext.RouteData.Values["controller"].ToString();
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Create", _Controller , new { id = Model.EmpSN }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.Partial("_EditArea", Model)
}

src/admin/Views/Employee/Edit.cshtml
@model admin.Models.EmployeeModel

@{
     string _Controller = Request.RequestContext.RouteData.Values["controller"].ToString();
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Update", _Controller, new { id = Model.EmpSN }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.Partial("_EditArea", Model)
}

src/admin/Views/Employee/List.cshtml
@using admin.Models;
@model admin.Models.EmployeeListModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    string AddUrl = RouteTable.Routes.GetVirtualPathForArea(ViewContext.RequestContext,
                    new RouteValueDictionary() { 
                        { "action" , "add" }
                    }).VirtualPath;
}
<!-- Modal -->
<div id="import" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">匯入員工資料</h3>
    </div>
    @using (Html.BeginForm("Import", "Employee", null, FormMethod.Post, 
        new { id ="f1", @class = "form-inline", style = "margin-bottom:0px", enctype = "multipart/form-data", target = "fileupload" })
    )
    {
        <div class="modal-body">
            @*<p>請選擇 excel 檔案 … (<a href="@Url.Content("~/App_Data/Employee.xls")">下載 Excel</a>)</p>*@
            <input type="file" name="f" />
        </div>
        <div class="modal-footer">
            <input class="btn" type="submit" value="上傳" />
            <button class="btn" data-dismiss="modal" aria-hidden="true">關閉</button>
        </div>
    }
    <script type="text/javascript">
        var excel = { };
        excel.onComplete = function (data){
            if (data.RS == 'OK') {
                alert('上傳成功');
                //document.forms['f1'].reset();
                //$('#import').modal('hide');
                location.href = '@Url.Content("~/Employee/List")';
            }
            else {
                alert(data.msg);
            }
        }
    </script>
    <iframe name="fileupload" style="display:none;"></iframe>
</div>
<!-- Modal End-->
<div class="well">
    <a class="btn btn-primary" href="@Url.Content(AddUrl)">新增</a>
    <a class="btn btn-primary" href="#import" data-toggle="modal">匯入資料</a>
</div>
<table class="table table-bordered">
    <thead>
        <tr>
            <th> </th>
            <th>員工編號</th>
            <th>姓名</th>
            <th>部門名稱</th>
            <th>角色</th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Data != null)
        {
            if (Model.Data.Count == 0)
            {
                <tr class="info">
                    <td colspan="10">查無資料</td>
                </tr>
            }
            foreach (var Row in Model.Data)
            {
                string EditUrl = RouteTable.Routes.GetVirtualPathForArea(ViewContext.RequestContext,
                    new RouteValueDictionary() { 
                        { "action" , "edit" },
                        { "id" , Row.EmpSN }
                    }).VirtualPath;
                string DeleteUrl = RouteTable.Routes.GetVirtualPathForArea(ViewContext.RequestContext,
                   new RouteValueDictionary() { 
                        { "action" , "delete" },
                        { "id" , Row.EmpSN }
                    }).VirtualPath;
                <tr>
                    <td>
                        <a class="btn" href="@Url.Content(EditUrl)"> <i class="icon-file"></i></a>
                    </td>
                    <td>@Row.EmpSN</td>
                    <td>@Row.Name</td>
                    <td>@Row.DepName</td>
                    <td style="width:300px;">
                        @{
                            foreach (int Value in Enum.GetValues(typeof(KpssRole)))
                            {
                                if ((Row.Permission & Value) == Value)
                                {
                                    string Name = Enum.GetName(typeof(KpssRole), Value);
                                    @Name <text>,</text>
                                }
                            }
                        }

                    </td>
                    
                    <td>
                        <a class="btn btn-danger" href="javascript:;"
                            onclick="javascript:if (confirm('確定要刪除嗎?')) { location.href='@Url.Content(DeleteUrl)';};"> 
                            <i class="icon-trash icon-white"></i></a>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr class="info">
                <td colspan="10">查無資料</td>
            </tr>
        }
    </tbody>
</table>
@Html.Partial("_Pager", (admin.Models.PagerModel)Model)

src/admin/Views/Employee/Selector.cshtml
@model admin.Models.EmployeeListModel
@{
    Layout = "~/Views/Shared/_MiniPageLayout.cshtml";
}

@foreach (var item in Model.Data)
{
    <p>@item</p>
}

src/admin/Views/Employee/_EditArea.cshtml
@using admin.Models;
@{
    string _Controller = Request.RequestContext.RouteData.Values["controller"].ToString();

    string _AreaName = null;

    if (ViewContext.RouteData.DataTokens.ContainsKey("area"))
    {
        _AreaName = ViewContext.RouteData.DataTokens["area"].ToString();
        _Controller = _AreaName + "/" + _Controller;
    }

    string _action = Request.RequestContext.RouteData.Values["action"].ToString();

}
@model admin.Models.EmployeeModel
<div class="editArea">
    @Html.ValidationSummary(true, "新增失敗")
    @Html.ValidationMessage(" ")
    <table border="0" cellpadding="0" cellspacing="0" class="table jamzoo-middle">
        <tbody>
            <tr>
                <td width="20%" class="star1">業務人員
                </td>
                <td>
                    @if (_action.ToLower() == "edit" || _action.ToLower() == "update")
                    {
                        @Model.EmpSN
                        @Html.HiddenFor(p => p.EmpSN)
                    }
                    else
                    {
                        @Html.TextBoxFor(p => p.EmpSN, new { @class = "span5", size = "30" })
                        @Html.ValidationMessageFor(p => p.EmpSN)
                    }
                </td>
            </tr>

            
            <tr>
                <td>區域
                </td>
                <td>
                    @Html.TextBoxFor(p => p.Area, new { @class = "span3", size = "30" })
                    @Html.ValidationMessageFor(p => p.Area)
                </td>

            </tr>

            <tr>
                <td>職稱
                </td>
                <td>
                    @Html.TextBoxFor(p => p.Title, new { @class = "span3", size = "30" })
                    @Html.ValidationMessageFor(p => p.Title)
                </td>

            </tr>

            <tr>
                <td>權責
                </td>
                <td>
                    @Html.TextBoxFor(p => p.PermissionTitle, new { @class = "span5", size = "30" })
                    @Html.ValidationMessageFor(p => p.PermissionTitle)
                </td>

            </tr>

            <tr>
                <td>部門
                </td>
                <td>
                    @Html.TextBoxFor(p => p.DepName, new { @class = "span3" })
                    @Html.ValidationMessageFor(p => p.DepName)
                </td>
            </tr>

            <tr>
                <td>Sales Code
                </td>
                <td>
                    @Html.TextBoxFor(p => p.SalesCode, new { @class = "span3" })
                    @Html.ValidationMessageFor(p => p.SalesCode)
                </td>
            </tr>

            <tr>
                <td>主管別
                </td>
                <td>
                    @Html.TextBoxFor(p => p.Manage1, new { @class = "span3", placeholder = "主管別一" })
                    @Html.ValidationMessageFor(p => p.SalesCode)
                    @Html.TextBoxFor(p => p.Manage2, new { @class = "span3", placeholder = "主管別二" })
                    @Html.ValidationMessageFor(p => p.SalesCode)
                    @Html.TextBoxFor(p => p.Manage3, new { @class = "span3", placeholder = "主管別三" })
                    @Html.ValidationMessageFor(p => p.SalesCode)
                </td>
            </tr>

            <tr>
                <td>員工姓名
                </td>
                <td>
                    @Html.TextBoxFor(p => p.Name, new { @class = "span5", size = "30" })
                    @Html.ValidationMessageFor(p => p.Name)
                </td>
            </tr>



            <tr>
                <td>英文全名
                </td>
                <td>
                    @Html.TextBoxFor(p => p.Name_en, new { @class = "span5", size = "30" })
                    @Html.ValidationMessageFor(p => p.Name_en)
                </td>
            </tr>

            <tr>
                <td>角色
                </td>
                <td>
                    @{
                        foreach (int Value in Enum.GetValues(typeof(KpssRole)))
                        {
                            string RoleName = Enum.GetName(typeof(KpssRole), Value);
                            bool IsChecked = ((Model.Permission & Value) == Value);
                        <label class="checkbox inline span5">
                            <input @(IsChecked ? "checked=checked" : "") type="checkbox"  name="Permissions" value="@Value" />@RoleName</label> 
                        }
                    }

                </td>
            </tr>

           @* <tr>
                <td>代理人
                </td>
                <td>
                    <div id="agentlist">
                    </div>
                    <script type="text/javascript">
                        var empSN = '@Model.EmpSN';
                        $(function () {
                            if (typeof (jamzoo.regauto) == "function") {
                                jamzoo.regauto($('#Number'), '@Url.Content("~/Customer/SearchByName")', 1);
                            }

                            getAgentsByEmpSN(empSN);
                        });

                        function getAgentsByEmpSN()
                        {
                            $.get(
                                '@Url.Content("~/CustomerAgent/List")', 
                                { empsn : empSN },
                                function(json)
                                {
                                    if (json.RS == 0)
                                    {
                                        for (var i = 0; i < json.data.length; i++) {
                                            addRow(json.data[i].number, json.data[i].customerName);
                                        }
                                    }
                                    else{
                                        alert(json.message);
                                    }
                                }, 
                                "json");
                        }

                        function addRow(number, customerName)
                        {
                            $('#agentlist')
                            .append(
                                $('<div />')
                                    .append(
                                        $('<span />').text(customerName))
                                    .append(
                                        $('<span />').text("(" + number + ")"))
                                    .append(
                                        $('<a />').attr('href', 'javascript:;').text(' 刪除').bind('click', function(){ 
                                            deleteAgentFromEmp(this, number);
                                        })
                                    )
                            );
                        }

                        function addAgentToEmpSN()
                        {
                            var number = $('#Number').val();
                            $.post(
                                '@Url.Content("~/CustomerAgent/Create")',
                                    { empsn : empSN, number : number },
                                    function (json)
                                    {
                                        if (json.RS == 0) {
                                            //OK
                                            addRow(json.data.number, json.data.customerName);
                                            $('#Number').val('');
                                        }
                                        else{
                                            alert(json.message);
                                        }
                                    },
                                    "json");
                            }

                            function deleteAgentFromEmp(sender, number)
                            {
                                $.post(
                                    '@Url.Content("~/CustomerAgent/Delete")',
                                    { empsn : empSN, number : number },
                                    function (json)
                                    {
                                        if (json.RS != 0) {
                                            alert(json.message);
                                        }
                                        else {
                                            $(sender).parent().remove();
                                        }
                                    },
                                    "json");
                            }

                    </script>
                    <input type="text" name="Number" id="Number" />
                    <input type="button" class="btn" value="新增" onclick="addAgentToEmpSN()" />
                </td>
                </tr>*@


                @*<tr>
					<td>
                       Email
					</td>
					<td>
						@Html.TextBoxFor(p => p.Email, new { @class = "span5" })
                        @Html.ValidationMessageFor(p => p.Email)
					</td>
				</tr>

                <tr>
					<td>
                        電話
					</td>
					<td>
						@Html.TextBoxFor(p => p.Tel, new { @class = "span5" })
                        @Html.ValidationMessageFor(p => p.Tel)
					</td>
				</tr>

                <tr>
					<td>
                       手機
					</td>
					<td>
						@Html.TextBoxFor(p => p.Mobile, new { @class = "span5" })
                        @Html.ValidationMessageFor(p => p.Mobile)
					</td>
				</tr>*@

            <tr>
                <td>登入帳號
                </td>
                <td>
                    @Model.EmpSN
                </td>
            </tr>

            <tr>
                <td>
                    Sales Office
                </td>
                <td>
                    @Html.TextBoxFor(p => p.SalesOffice, new { @class = "span5" })
                    @Html.ValidationMessageFor(p => p.SalesOffice)
                </td>
            </tr>

            <tr>
                <td>
                    Sales Group
                </td>
                <td>
                    @Html.TextBoxFor(p => p.SalesGroup, new { @class = "span5" })
                    @Html.ValidationMessageFor(p => p.SalesGroup)
                </td>
            </tr>

            <tr>
                <td>
                    Sales Person
                </td>
                <td>
                    @Html.TextBoxFor(p => p.SalesPerson, new { @class = "span5" })
                    @Html.ValidationMessageFor(p => p.SalesPerson)
                </td>
            </tr>

            <tr>
                <td>
                    Sales Employee
                </td>
                <td>
                    @Html.TextBoxFor(p => p.SalesEmployee, new { @class = "span5" })
                    @Html.ValidationMessageFor(p => p.SalesEmployee)
                </td>
            </tr>

            @* <tr>
					<td>
                       Device 編號
					</td>
					<td>
                        @Model.DeviceID
					</td>
				</tr>

                 <tr>
					<td>
                        Mac
					</td>
					<td>
                        @Model.Mac
					</td>
				</tr>*@


        </tbody>
    </table>
</div>



<div class="BTNcenter">
    <input type="submit" class="btn" id="btn_submit" name="btn_submit" value="儲存送出" onclick="javascript:return confirm('確定儲存送出嗎?');">
    <input type="button" class="btn" id="btn_cancle" name="btn_cancle" value="取消變更" onclick="javascript:if (confirm('確定取消變更嗎?')){window.location.href='@Url.Content("~/" + _Controller + "/List")        ';}">
</div>