src/admin/Areas/app/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using admin.Filter;
using admin.Models;
using admin.Extensions; 

namespace admin.Models
{
    public class CustomerCriteria
    {
        //電話
        public string Phone { get; set; }

        //客戶名稱
        public string Name { get; set; }

        //統編
        public string Number { get; set; }

        //地區編號
        public string Area { get; set; }
    }
}

namespace admin.Areas.app.Controllers
{
    using Service;
    using Models;

    public class CustomerController : BaseAPIController
    {
        CustomerService CusService;

        public CustomerController()
        {
            CusService = new CustomerService();
        }

        [HttpGet]
        [KpssAuthorize(KpssRole.區業務主管, KpssRole.駐區業務)]
        public ActionResult Training(AccountModel Emp, string EmpId, string c, int page = 1, int pageSize = 50)
        {
            CustomerTrainingService TrainingService = new CustomerTrainingService();
            CustomerTrainingListModel Model = null;
            try
            {
                if (Emp.IsInRoles(KpssRole.區業務主管))
                {
                    Model = TrainingService.GetListFor主管(Emp.SN, EmpId, c, new CustomerTrainingListModel() { Page = page, PageSize = pageSize });
                }
                else
                {
                    //非主管
                    Model = TrainingService.GetList(Emp.SN, c, new CustomerTrainingListModel() { Page = page, PageSize = pageSize });
                }

                return Json(
                    new { 
                        succeed = 1, 
                        data = Model.Data.Select(p => new {
                            Id = p.Id,
                            Number = p.Number,
                            Date = p.Date.Date.ToString("yyyy/MM/dd"),
                            Subject = p.Subject,
                            Teacher = p.Teacher,
                            Summary = p.Summary,
                            StdCount = p.StdCount,
                            Suggestion = p.Suggestion,
                            React = p.React,
                            IsSales = p.IsSales,
                            CreateDate = p.CreateDate.ToString("yyyy/MM/dd HH:mm:ss")
                        })
                    }, 
                    JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(
                    new { succeed = 0, msg = ex.Message}, 
                    JsonRequestBehavior.AllowGet);
            }

        }
        

        //回傳 Sqlite
        [HttpGet]
        [KpssAuthorize(KpssRole.區業務主管, KpssRole.駐區業務)]
        public ActionResult List(AccountModel Emp)
        {
            try
            {
                List<CustomerModel> Data = new List<CustomerModel>();

                if (Emp.IsInRoles(KpssRole.區業務主管))
                {
                    Data = CusService.GetAll();
                }
                else//業務
                {
                    Data = CusService.GetAllByEmp(Emp.SN);
                }

                return Json(Data, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    succeed = 0,
                    msg = ex.Message
                }, JsonRequestBehavior.AllowGet);
            }
          
        }

        //查詢
        // GET: /app/customer/query
        [HttpGet]
        [KpssAuthorize(KpssRole.區業務主管, KpssRole.駐區業務)]
        public ActionResult Query(AccountModel Emp, CustomerCriteria Criteria)
        {
            try
            {
                var Query = CusService.Query(
                    Emp.SN,
                    Criteria.Phone,
                    Criteria.Name,
                    Criteria.Number, Criteria.Area);

                return Json(new
                {
                    succeed = 1,
                    msg = "成功",
                    customers = Query.ToList()
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    succeed = 0,
                    msg = ex.Message
                });
            }
        }


        //新增業務資料
        // POST : /app/customer/create
        [HttpPost]
        [KpssAuthorize(KpssRole.區業務主管, KpssRole.駐區業務)]
        public ActionResult Create(AccountModel Emp, CustomerModel Customer)
        {
            Dictionary<string, object> ErrorMessage = new Dictionary<string, object>();
            if (ModelState.IsValid)
            {
                //看誰登入, 就直接塞給他
                Customer.SalesOffice = Emp.SalesOffice;
                Customer.SalesCode = Emp.SalesCode;

                if (CusService.Create(Emp.SN, Customer, out ErrorMessage))
                {
                    return Json(new
                    {
                        succeed = 1,
                        msg = "成功"
                    }, JsonRequestBehavior.AllowGet);
                }

                return Json(new
                {
                    succeed = 0,
                    msg = (ErrorMessage.Keys.Count() > 0) ? ErrorMessage.FirstOrDefault().Value : "N/A"
                }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new
                {
                    succeed = 0,
                    msg = ModelState.GetErrorsString(",")
                }, JsonRequestBehavior.AllowGet);
            }
        }

        //修改客戶資料
        [HttpPost]
        [KpssAuthorize(KpssRole.區業務主管, KpssRole.駐區業務)]
        public ActionResult Update(AccountModel Emp, CustomerModel Customer)
        {
            Dictionary<string, object> ErrorMessage = new Dictionary<string,object>();

            if (CusService.Update(Emp.SN, Customer, out ErrorMessage))
            {
                return Json(new {
                    succeed = 1,
                    msg = "成功"
                }, JsonRequestBehavior.AllowGet);
            }
            
            return Json(new {
                succeed = 0,
                msg = (ErrorMessage.Keys.Count() > 0) ?ErrorMessage.FirstOrDefault().Value:"N/A"
            }, JsonRequestBehavior.AllowGet);
        }

        //新增照片
        [HttpPost]
        [KpssAuthorize(KpssRole.區業務主管, KpssRole.駐區業務)]
        public ActionResult AddPhoto(AccountModel Emp, string Number, string Title, HttpPostedFileBase Photo)
        {
            Dictionary<string, object> ErrorMessage = new Dictionary<string,object>();

            if (CusService.AddPhoto(Emp.SN, Number, Title, Photo, out ErrorMessage))
            {
                return Json(new {
                    succeed = 1,
                    msg = "成功"
                }, JsonRequestBehavior.AllowGet);
            }

            return Json(new
            {
                succeed = 0,
                msg = (ErrorMessage.Keys.Count() > 0) ? ErrorMessage.FirstOrDefault().Value : "N/A"
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

src/admin/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using admin.Extensions;

namespace admin.Controllers
{
    using Models;
    using Service;

    [Authorize(Roles = "管理員,總經理,區業務主管,駐區業務")]
    public class CustomerController : Controller
    {
         protected CustomerService Service;

        public CustomerController()
        {
            Service = new CustomerService();
        }

        //
        // GET: /Customer/List
        public ActionResult List(CustomerListModel criteria)
        {
            try
            {
                CustomerListModel model = Service.GetList(User.Identity.Name, criteria);

                return View(model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(" ", ex.Message);
            }
            return View(criteria);
        }

        public ActionResult Add()
        {
            CustomerModel entity = new CustomerModel();

            return View(entity);
        }

        [HttpPost]
        public ActionResult Import(HttpPostedFileBase f)
        {
            Dictionary<string, object> dErrMsg = new Dictionary<string, object>();

            if (f != null)
            {
                if (System.IO.Path.GetExtension(f.FileName).ToLower().Equals(".xlsx") ||
                    System.IO.Path.GetExtension(f.FileName).ToLower().Equals(".xls")
                    )
                {
                    string strFileName = System.IO.Path.GetFileName(f.FileName);
                    string strAbsFilePath = Server.MapPath("~/App_Data/Temp/" + strFileName);

                    f.SaveAs(strAbsFilePath);

                    Service.ExcelImport(strAbsFilePath, out dErrMsg);
                }
            }
            else
            {
                dErrMsg.Add("file", "無上傳檔案");
            }
            string strRs = dErrMsg.Keys.Count() == 0 ? "OK" : "Error";
            string strErrMsg = dErrMsg.Keys.Count() == 0 ? "" : dErrMsg[dErrMsg.Keys.FirstOrDefault()].ToString();

            return Content("<script type='text/javascript'>parent.excel.onComplete({RS:'" + strRs + "',msg:'" + strErrMsg + "'});</script>");
        }

        [HttpPost]
        public ActionResult Create(string EmpSN, CustomerModel model)
        {
            if (ModelState.IsValid)
            {
                Dictionary<string, object> ErrorMessage = new Dictionary<string, object>();
                try
                {
                    if (Service.Create(EmpSN, model, out ErrorMessage))
                    {
                        return RedirectToAction("List"); 
                    }

                    ModelState.AddModelError(" ", "新增失敗");
                    
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(" ", ex.Message);
                }
            }
            return View("Add", model);
        }

        public ActionResult Edit(string id)
        {
            CustomerModel model = Service.Get(id);
            if (model != null)
            {
                return View(model);
            }
            else
            {
                return Content("查無資料");
            }
        }

        [HttpPost]
        public ActionResult Update(CustomerModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Dictionary<string,Object> dErrMsg = new Dictionary<string,object>();

                    if (Service.Update(User.Identity.Name, model, out dErrMsg))
                    {
                        return RedirectToAction("List"); 
                    }
                    else
                    {
                        ModelState.AddModelError(" ", "修改失敗 : " + dErrMsg[dErrMsg.Keys.LastOrDefault()]);
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(" ", ex.Message);
                }
            }
            return View("Edit", model);
        }

        public ActionResult Delete(string id)
        {
            try
            {
                if (Service.Delete(User.Identity.Name, id))
                {
                    TempData["delete"] = true;
                }
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(" ", ex.Message);
                TempData["error"] = false;
                TempData["message"] = ex.Message;
            }
            return RedirectToAction("List");
        }

        //給自動完成用的 action 
        //GET: Employee/SearchByName
        public ActionResult SearchByName(string term)
        {
            var Query = Service.GetList(User.Identity.Name, 
                new CustomerListModel() {
                    Name = term
                });

    
            if (Query.Data != null)
            {
                var o_query = Query.Data.Select(p => new AutocompleteModel()
                {
                    id = p.Number,
                    label = string.Format("{0}({1})", p.Name, p.Number),
                    value = p.Number
                });

                return Json(o_query.ToList(), JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Content(string.Empty);
            }
        }
    }
}

src/admin/Views/Customer/Add.cshtml
@model admin.Models.CustomerModel

@{
     string _Controller = Request.RequestContext.RouteData.Values["controller"].ToString();
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Create", _Controller , new { id = Model.EmpSN }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.Partial("_EditArea", Model)
}

src/admin/Views/Customer/Edit.cshtml
@model admin.Models.CustomerModel

@{
     string _Controller = Request.RequestContext.RouteData.Values["controller"].ToString();
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Update", _Controller, new { id = Model.Number }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.Partial("_EditArea", Model)
}

src/admin/Views/Customer/List.cshtml
@model admin.Models.CustomerListModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    string AddUrl = RouteTable.Routes.GetVirtualPathForArea(ViewContext.RequestContext,
                   new RouteValueDictionary() { 
                        { "action" , "add" }
                    }).VirtualPath;

    string _Controller = string.Empty;

    if (ViewContext.RouteData.Values["Controller"] != null)
    {
        _Controller = ViewContext.RouteData.Values["Controller"].ToString();
    }
}

<!-- Modal -->
<div id="import" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">匯入客戶資料</h3>
  </div>
    @using (Html.BeginForm("Import", "Customer", null, FormMethod.Post,
        new { id = "f1", @class = "form-inline", style = "margin-bottom:0px", enctype = "multipart/form-data", target = "fileupload" })
    )
    {
        <div class="modal-body">
@*            <p>請選擇 excel 檔案 … (<a href="@Url.Content("~/App_Data/Customer.xls")">下載 Excel</a>)</p>*@
            <input type="file" name="f" />
        </div>
        <div class="modal-footer">
            <input class="btn" type="submit" value="上傳" />
            <button class="btn" data-dismiss="modal" aria-hidden="true">關閉</button>
        </div>
    }
    <script type="text/javascript">
        var excel = {};
        excel.onComplete = function (data) {
            if (data.RS == 'OK') {
                alert('上傳成功');
                //document.forms['f1'].reset();
                //$('#import').modal('hide');
                location.href = '@Url.Content("~/Customer/List")';
            }
            else {
                alert(data.msg);
            }
        }
    </script>
    <iframe name="fileupload" style="display:none;"></iframe>
</div>
<!-- Modal End-->

<script type="text/javascript">
    $(function () {
        if (typeof (jamzoo.regauto) == "function") {
            jamzoo.regauto($('#EmpSN'), '@Url.Content("~/Employee/SearchByName")', 1);
            jamzoo.regauto($('#Number'), '@Url.Content("~/Customer/SearchByName")', 1);
        }
    });
</script>

<div class="well">
    @using (Html.BeginForm("List", _Controller, FormMethod.Get))
    {
        <a class="btn btn-primary" href="@Url.Content(AddUrl)">新增客戶</a>
        <a class="btn btn-primary" href="#import" data-toggle="modal">匯入資料</a>
        <p>
        @Html.TextBoxFor(p => p.Area, new { @class = "input-medium", style="margin:2px 2px;", placeholder = "地區" })
        @Html.TextBoxFor(p => p.Number, new { @class = "input-medium", style="margin:2px 2px;", placeholder = "客戶編號" })
        @Html.TextBoxFor(p => p.CustomerName, new { @class = "input-medium", style="margin:2px 2px;", placeholder = "客戶名稱" })
        @Html.TextBoxFor(p => p.EmpSN, new { @class = "input-medium", style="margin:2px 2px;", placeholder = "業務編號" })
        <input type="submit" class="btn" value="查詢" />
        </p>
    }
</div>
@*<div class="well">
    <a class="btn btn-primary" href="@Url.Content(AddUrl)">新增</a>
    <a class="btn btn-primary" href="#import" data-toggle="modal">匯入資料</a>
</div>*@
@if (TempData["error"] != null)
{
    <div class="alert">
@*        <button type="button" class="close" data-dismiss="alert">&times;</button>*@
    <strong></strong> @TempData["message"]
    </div>
}
<div style="text-align:right; ">
總共： @Model.TotalRecords 筆
</div>
<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width:300px;"> </th>
            <th>客戶名稱</th>
            <th>Sap Code</th>
            <th>地址</th>
            <th>電話</th>
            <th style="width:60px"></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Data != null)
        {
            if (Model.Data.Count == 0)
            {
                <tr class="info">
                    <td colspan="6">查無資料</td>
                </tr>
            }
            foreach (var Row in Model.Data)
            {
                string EditUrl = RouteTable.Routes.GetVirtualPathForArea(ViewContext.RequestContext,
                    new RouteValueDictionary() { 
                        { "action" , "edit" },
                        { "id" , Row.Number }
                    }).VirtualPath;
                string DeleteUrl = RouteTable.Routes.GetVirtualPathForArea(ViewContext.RequestContext,
                   new RouteValueDictionary() { 
                        { "action" , "delete" },
                        { "id" , Row.Number }
                    }).VirtualPath;

                string 拜訪記錄Url = RouteTable.Routes.GetVirtualPathForArea(ViewContext.RequestContext,
                   new RouteValueDictionary() { 
                        { "controller" , "VisitLog" },
                        { "action" , "List" },
                        { "SearchText" , Row.Number }
                    }).VirtualPath;

                string 待辦事項Url = RouteTable.Routes.GetVirtualPathForArea(ViewContext.RequestContext,
                   new RouteValueDictionary() { 
                        { "controller" , "CustomerMemo" },
                        { "action" , "List" },
                        { "SearchText" , Row.Number }
                    }).VirtualPath;

                string 交辦事項Url = RouteTable.Routes.GetVirtualPathForArea(ViewContext.RequestContext,
                   new RouteValueDictionary() { 
                        { "controller" , "CustomerAssignment" },
                        { "action" , "List" },
                        { "SearchText" , Row.Number }
                    }).VirtualPath;

                string 聯絡人Url = RouteTable.Routes.GetVirtualPathForArea(ViewContext.RequestContext,
                   new RouteValueDictionary() { 
                        { "controller" , "CustomerContactInfo" },
                        { "action" , "List" },
                        { "SearchText" , Row.Number }
                    }).VirtualPath;
                <tr>
                    <td>
                        <a class="btn" href="@Url.Content(EditUrl)" title="編輯">編輯</a>
                        <a class="btn" href="@Url.Content(拜訪記錄Url)" title="拜訪記錄">拜訪</a>
                        <a class="btn" href="@Url.Content(待辦事項Url)" title="待辦事項">待辦</a>
                        <a class="btn" href="@Url.Content(交辦事項Url)" title="交辦事項">交辦</a>
                        <a class="btn" href="@Url.Content(聯絡人Url)" title="聯絡人">聯絡人</a>
                    </td>
                    <td>@Row.Name</td>
                    <td>@Row.SapCode</td>
                    <td>@Row.TransportAddr</td>
                    <td>@Row.Tel</td>
                    <td>
                        <a class="btn btn-danger" href="javascript:;"
                            onclick="javascript:if (confirm('確定要刪除嗎?')) { location.href='@Url.Content(DeleteUrl)';};"> 
                        刪除</a>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr class="info">
                <td colspan="6">查無資料</td>
            </tr>
        }
    </tbody>
</table>
@*@Html.Partial("_Pager", (admin.Models.PagerModel)Model)*@


<div class="pagination pagination-centered">
    <ul>
    @Html.Pager(Model.PageSize, Model.Page, Model.TotalRecords).Options(o => o
        .DisplayTemplate("PagerTemplate")
        .AddRouteValue("PageSize", Model.PageSize)
        .AddRouteValue("EmpSN", Model.EmpSN)
        .AddRouteValue("Area", Model.Area)
        .AddRouteValue("Number", Model.Number)
        )
    </ul>
</div>