src/admin/Areas/app/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using admin.Models;
using System.Net.Mail;
using System.Text;
using System.Net;

namespace admin.Areas.app.Controllers
{
    using System.IO;
    using Filter;
    using Service;

    [ApiAttribute]
    public class ProductController : BaseAPIController
    {
        KpiService Service;

        public ProductController()
        {
            Service = new KpiService();
        }

        [KpssAuthorize(KpssRole.區業務主管, KpssRole.業務秘書, KpssRole.駐區業務)]
        public ActionResult Brands(AccountModel emp)
        {
            ProductPage m = new ProductPage();
            ProductService s = new ProductService();
            m.Brands = s.GetBrands();
            return View(m);
        }

        [KpssAuthorize(KpssRole.區業務主管, KpssRole.業務秘書, KpssRole.駐區業務)]
        public ActionResult Category(AccountModel emp, string Brand)
        {
            ProductPage m = new ProductPage();
            ProductService s = new ProductService();
            m.Serials = s.GetSerialsByBrand(Brand);
            m.Brand = Brand;

            return View(m);
        }

        // 取得產品的頁面
        // GET: /app/product/index?token=
        [KpssAuthorize(KpssRole.區業務主管, KpssRole.業務秘書, KpssRole.駐區業務)]
        public ActionResult Index(AccountModel emp,string Brand, string Serial)
        {
            return View(new OrderForm() {
                name = emp.Name,
                mail = emp.Email,
                serial = Serial,
                brand = Brand
            });
        }

        // 購物車頁面
        // GET: /app/product/cars?token=
        [KpssAuthorize(KpssRole.區業務主管, KpssRole.業務秘書, KpssRole.駐區業務)]
        public ActionResult Cars(AccountModel emp, string brand, string serial)
        {
            return View(new OrderForm()
            {
                name = emp.Name,
                mail = emp.Email,
                brand = brand,
                serial = serial
            });
        }


        [KpssAuthorize(KpssRole.區業務主管, KpssRole.業務秘書, KpssRole.駐區業務)]
        public ActionResult List(AccountModel emp, string serial)
        {
            ProductService s = new ProductService();

            var Query = s.GetList(emp.SN, "", serial, new ProductListModel());

            return Json(Query.Data.Take(100).ToList(), JsonRequestBehavior.AllowGet);
        }

        // 業務主管 用來查詢業務業績
        // GET: /app/product/order?token=
        [HttpPost]
        [KpssAuthorize(KpssRole.區業務主管, KpssRole.業務秘書, KpssRole.駐區業務)]
        public ActionResult Order(AccountModel emp)
        {
            string MailLogPath = Server.MapPath("~/App_Data/Mail/Log/mail.txt");

            string documentContents;

            if (Request.InputStream != null)
                Request.InputStream.Position = 0;

            using (Stream receiveStream = Request.InputStream)
            {
                using (StreamReader readStream = new StreamReader(receiveStream))
                {
                    documentContents = readStream.ReadToEnd();
                }
            }
            string strJsonOrder = documentContents;

            System.Web.Script.Serialization.JavaScriptSerializer ser = new System.Web.Script.Serialization.JavaScriptSerializer();
            OrderForm of = ser.Deserialize<OrderForm>(strJsonOrder);
            try
            {
                send_email(
                    of != null ? of.getCSV() : string.Empty, 
                    "[歌薇]" + emp.Name + "的產品追加單",
#if (DEBUG)
 //"lucien.liu@jamzoo.com.tw",
  //"niko.chen@kpss-hair.com.tw",
  "eorder@kpss-hair.com.tw",
#endif
#if (!DEBUG)
                    "eorder@kpss-hair.com.tw",
#endif

 new string[] { of.GetContentCSV() }
                    );
                //MailLog(MailLogPath, "發送成功");

                return Json(new { rs = "OK" });
            }
            catch (Exception ex)
            {
                //MailLog(MailLogPath, ex.Message);
                if (ex.InnerException != null)
                { 
                    return Json(new { rs = ex.InnerException.Message });
                }
                else
                {
                    return Json(new { rs = ex.Message });
                }
            }

            
        }

        public static void MailLog(string Path, string Message)
        {
            using (StreamWriter w = System.IO.File.AppendText("log.txt"))
            {
                Log("Test1", w);
            }
        }

        public static void Log(string logMessage, TextWriter w)
        {
            w.Write("\r\nLog Entry : ");
            w.WriteLine("{0} {1}", DateTime.Now.ToLongTimeString(),
                DateTime.Now.ToLongDateString());
            w.WriteLine("  :");
            w.WriteLine("  :{0}", logMessage);
            w.WriteLine("-------------------------------");
        }

        public void send_email(string msg, string mysubject, string address, string[] attachmentContent)
        {
            if (!string.IsNullOrEmpty(msg))
            {
                MailMessage message = new MailMessage("Servcie@kpss.com.tw", address);  //MailMessage(寄信者, 收信者)
                message.IsBodyHtml = false;
                message.BodyEncoding = System.Text.Encoding.UTF8;                       //E-mail 編碼
                message.Subject = mysubject;                                            //E-mail 主旨
                message.Body = msg;                                                     //E-mail 內容
                message.Bcc.Add(new MailAddress("ajen.chen@jamzoo.com.tw", "ajen.chen"));
                message.Bcc.Add(new MailAddress("yc.hsieh@jamzoo.com.tw", "yc.hsieh"));
                message.Bcc.Add(new MailAddress("lucien.liu@jamzoo.com.tw", "lucien.liu"));

                foreach (var att in attachmentContent)
                {
                    byte[] b = Encoding.GetEncoding("Big5").GetBytes(att);
                    MemoryStream ms = new MemoryStream(b);
                    message.Attachments.Add(new Attachment(ms, mysubject + ".csv"));
                }
                SmtpClient smtpClient = new SmtpClient("127.0.0.1", 25);                //設定 E-mail Server 和 port
                smtpClient.Send(message);
            }
        }
    }
}


namespace admin.Models
{
    public class ProductPage
    {
        public List<SelectListItem> Brands { get; set; }

        public string Brand { get; set; }

        public List<SelectListItem> Serials { get; set; }
    }

    //訂購單
    public class OrderForm
    {
        public string mail { get; set; }
        public string name { get; set; }
        public string mobile { get; set; }
        public string addr { get; set; }

        public string serial { get; set; }
        public string brand { get; set; }

        public List<Dictionary<string, object>> pros { get; set; }

        public string GetContentCSV()
        {
            StringBuilder sb = new StringBuilder();

            foreach (var r in pros)
            {
                if (r.Keys.Contains("amt"))
                {
                    int iAmt = 0;
                    Int32.TryParse(r["amt"].ToString(), out iAmt);
                    int Price = 0;
                    Int32.TryParse(r["price"].ToString(), out Price);
                    if (iAmt > 0)
                    {
                        string strRow = string.Empty;
                        foreach (var k in r.Keys)
                        {
                            if (r[k] != null)
                            {
                                if (k == "price")
                                {
                                    int Total = iAmt * Price;
                                    strRow += Total.ToString();
                                }
                                else
                                {
                                    strRow += r[k].ToString();
                                }
                            }
                            strRow += ",";
                        }
                        sb.AppendLine(strRow);

                    }
                }
            }

            return sb.ToString();
        }

        public string getCSV()
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("姓名:" + name);
            sb.AppendLine("信箱:" + mail);
            sb.AppendLine("手機:" + mobile);
            sb.AppendLine("地址:" + addr);
            sb.AppendLine("=======================");

            foreach (var r in pros)
            {
                if (r.Keys.Contains("amt"))
                {
                    int iAmt = 0;
                    Int32.TryParse(r["amt"].ToString(), out iAmt);
                    int Price = 0;
                    Int32.TryParse(r["price"].ToString(), out Price);
                    if (iAmt > 0)
                    {
                        string strRow = string.Empty;
                        foreach (var k in r.Keys)
                        {
                            if (r[k] != null)
                            {
                                if (k == "price")
                                {
                                    int Total = iAmt * Price;
                                    strRow += Total.ToString();
                                }
                                else
                                {
                                    strRow += r[k].ToString();
                                }
                                
                            }
                            strRow += ",";
                        }
                        sb.AppendLine(strRow);

                    }
                }
            }
            return sb.ToString();
        }
    }
}

src/admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using admin.Extensions;

namespace admin.Controllers
{
    using Models;
    using Service;

    [Authorize(Roles = "管理員,總經理,區業務主管,駐區業務")]
    public class ProductController : Controller
    {
        protected ProductService Service;

        public ProductController()
        {
            Service = new ProductService();
        }

        [HttpPost]
        public ActionResult Import(HttpPostedFileBase f)
        {
            Dictionary<string, object> dErrMsg = new Dictionary<string, object>();

            if (f != null)
            {
                if (System.IO.Path.GetExtension(f.FileName).ToLower().Equals(".xlsx") ||
                    System.IO.Path.GetExtension(f.FileName).ToLower().Equals(".xls")
                    )
                {
                    string strFileName = System.IO.Path.GetFileName(f.FileName);
                    string strAbsFilePath = Server.MapPath("~/App_Data/Temp/" + strFileName);

                    f.SaveAs(strAbsFilePath);

                    Service.ExcelImport(strAbsFilePath, out dErrMsg);
                }
            }
            else
            {
                dErrMsg.Add("file", "無上傳檔案");
            }
            string strRs = dErrMsg.Keys.Count() == 0 ? "OK" : "Error";
            string strErrMsg = dErrMsg.Keys.Count() == 0 ? "" : dErrMsg[dErrMsg.Keys.FirstOrDefault()].ToString();

            return Content("<script type='text/javascript'>parent.excel.onComplete({RS:'" + strRs + "',msg:'" + strErrMsg + "'});</script>");
        }

        //
        // GET: /Product/List
        public ActionResult List(string EmpId, ProductListModel criteria)
        {
            try
            {
                ProductListModel model = Service.GetList(User.Identity.Name, EmpId, string.Empty, criteria);

                return View(model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(" ", ex.Message);
            }

            return View(criteria);
        }

        public ActionResult Add()
        {
            ProductModel entity = new ProductModel();

            return View(entity);
        }

        [HttpPost]
        public ActionResult Create(string EmpSN, ProductModel model)
        {
            if (ModelState.IsValid)
            {
                Dictionary<string, object> ErrorMessage = new Dictionary<string, object>();
                try
                {
                    if (Service.Create(EmpSN, model, out ErrorMessage))
                    {
                        return RedirectToAction("List");
                    }

                    ModelState.AddModelError(" ", "新增失敗");

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(" ", ex.Message);
                }
            }
            return View("Add", model);
        }

        public ActionResult Edit(string id)
        {
            ProductModel model = Service.Get(User.Identity.Name, id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Update(ProductModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Dictionary<string, Object> dErrMsg = new Dictionary<string, object>();

                    if (Service.Update(User.Identity.Name, model, out dErrMsg))
                    {
                        return RedirectToAction("List");
                    }
                    else
                    {
                        ModelState.AddModelError(" ", "修改失敗 : " + dErrMsg[dErrMsg.Keys.LastOrDefault()]);
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(" ", ex.Message);
                }
            }
            return View("Edit", model);
        }

        public ActionResult Delete(string id)
        {
            try
            {
                if (Service.Delete(User.Identity.Name, id))
                {
                    TempData["delete"] = true;
                }
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(" ", ex.Message);
            }
            return RedirectToAction("List");
        }
    }
}

src/admin/Views/Product/Add.cshtml
@model admin.Models.CustomerModel

@{
     string _Controller = Request.RequestContext.RouteData.Values["controller"].ToString();
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Create", _Controller , new { id = Model.EmpSN }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.Partial("_EditArea", Model)
}

src/admin/Views/Product/Edit.cshtml
@model admin.Models.ProductModel

@{
     string _Controller = Request.RequestContext.RouteData.Values["controller"].ToString();
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Update", _Controller, new { id = Model.Id }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.Partial("_EditArea", Model)
}

src/admin/Views/Product/List.cshtml
@model admin.Models.ProductListModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    string AddUrl = RouteTable.Routes.GetVirtualPathForArea(ViewContext.RequestContext,
                   new RouteValueDictionary() { 
                        { "action" , "add" }
                    }).VirtualPath;

    string _Controller = string.Empty;

    if (ViewContext.RouteData.Values["Controller"] != null)
    {
        _Controller = ViewContext.RouteData.Values["Controller"].ToString();
    }
}

<!-- Modal -->
<div id="import" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">匯入客戶資料</h3>
  </div>
    @using (Html.BeginForm("Import", "Product", null, FormMethod.Post,
        new { id = "f1", @class = "form-inline", style = "margin-bottom:0px", enctype = "multipart/form-data", target = "fileupload" })
    )
    {
        <div class="modal-body">
            <p>請選擇 excel 檔案 … (<a href="@Url.Content("~/App_Data/Product.xls")">下載 Excel</a>)</p>
            <input type="file" name="f" />
        </div>
        <div class="modal-footer">
            <input class="btn" type="submit" value="上傳" />
            <button class="btn" data-dismiss="modal" aria-hidden="true">關閉</button>
        </div>
    }
    <script type="text/javascript">
        var excel = {};
        excel.onComplete = function (data) {
            if (data.RS == 'OK') {
                alert('上傳成功');
                document.forms['f1'].reset();
                $('#import').modal('hide');
            }
            else {
                alert(data.msg);
            }
        }
    </script>
    <iframe name="fileupload" style="display:none;"></iframe>
</div>
<!-- Modal End-->

<div class="well">
     @using (Html.BeginForm("List", _Controller, FormMethod.Get))
    {
    @Html.TextBoxFor(p => p.SearchText, new { @class = "input-medium", style="margin-bottom:0px;" })
    <input type="submit" class="btn" value="查詢" />
    <a class="btn btn-primary" href="#import" data-toggle="modal">匯入資料</a>
    }
</div>
<table class="table table-bordered">
    <thead>
        <tr>
            <th></th>
            <th>產品編號</th>
            <th>品牌</th>
            <th>類別</th>
            <th>子類別</th>
            <th>名稱</th>
            <th>型號</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Data != null)
        {
            if (Model.Data.Count == 0)
            {
                <tr class="info">
                    <td colspan="8">查無資料</td>
                </tr>
            }
            foreach (var Row in Model.Data)
            {
                string EditUrl = RouteTable.Routes.GetVirtualPathForArea(ViewContext.RequestContext,
                    new RouteValueDictionary() { 
                        { "action" , "edit" },
                        { "id" , Row.Id }
                    }).VirtualPath;
                string DeleteUrl = RouteTable.Routes.GetVirtualPathForArea(ViewContext.RequestContext,
                   new RouteValueDictionary() { 
                        { "action" , "delete" },
                        { "id" , Row.Id }
                    }).VirtualPath;
                <tr>
                    <td>
                        <a class="btn" href="@Url.Content(EditUrl)"> <i class="icon-file"></i></a>
                    </td>
                    <td>@Row.SN</td>
                    <td>@Row.Brand</td>
                    <td>@Row.Type</td>
                    <td>@Row.Serial</td>
                    <td>@Row.Pname</td>
                    <td>@Row.Spec</td>
                    <td>
                        <a class="btn btn-danger" href="javascript:;"
                            onclick="javascript:if (confirm('確定要刪除嗎?')) { location.href='@Url.Content(DeleteUrl)';};"> 
                            <i class="icon-trash icon-white"></i></a>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr class="info">
                <td colspan="8">查無資料</td>
            </tr>
        }
    </tbody>
</table>
@*@Html.Partial("_Pager", (admin.Models.PagerModel)Model)*@

<div class="pagination pagination-centered">
    <ul>
    @Html.Pager(Model.PageSize, Model.Page, Model.TotalRecords).Options(o => o
        .DisplayTemplate("PagerTemplate")
        .AddRouteValue("PageSize", Model.PageSize)
        )
    </ul>
</div>

src/admin/Views/Product/_EditArea.cshtml
@{
    string _Controller = Request.RequestContext.RouteData.Values["controller"].ToString();
    
    string _AreaName = null;

    if (ViewContext.RouteData.DataTokens.ContainsKey("area"))
    { 
        _AreaName = ViewContext.RouteData.DataTokens["area"].ToString();
        _Controller = _AreaName + "/" + _Controller; 
    }

    string _Action = Request.RequestContext.RouteData.Values["action"].ToString();
    string _Model = "add";

    if (_Action.ToLower()=="edit" || _Action.ToLower() == "update")
    {
        _Model = "edit";
    }
}

@model admin.Models.ProductModel
    <div class="editArea">
		@Html.ValidationSummary(true, "新增失敗")
        <table border="0" cellpadding="0" cellspacing="0" class="table jamzoo-middle">
            <tbody>
                <tr>
					<td width="20%" class="star1">
                        產品編號
					</td>
					<td>
                        @if (_Model == "edit")
                        {
                            @Model.SN
						    @Html.HiddenFor(p => p.SN)
                        }
                        else
                        {
                            @Html.TextBoxFor(p => p.SN)
                        }
					</td>
				</tr>

                <tr>
					<td>
                        品牌 
					</td>
					<td>
                        @Html.TextBoxFor(p => p.Brand)
					</td>
				</tr>

				<tr>
					<td>
                        產品類別
					</td>
					<td>
                        <div class="form-inline">
                        @Html.HiddenFor(p => p.Type)
                        @{
                            string[] aryType = { "染劑", "護染", "冷燙" };

                            foreach (var r in aryType)
                            {
                                <label class="checkbox">
                                    <input type="checkbox" name="types" value="@r" @(Model.Type.Contains(r) ? "checked=checked":"") /> @r
@*                                    @Html.CheckBox("Types", Model.Type.Contains(r), new { value = r })@r*@
                                </label>
                            }
                        }
                        </div>
					</td>
				</tr>

                <tr>
					<td>
                        子類別
					</td>
					<td>
						@Html.TextBoxFor(p => p.Serial, new { @class = "span5", size = "30"})
						@Html.ValidationMessageFor(p => p.Serial)
					</td>
				</tr>

				<tr>
					<td>
                        產品名稱 
					</td>
					<td>
						@Html.TextBoxFor(p => p.Pname, new { @class = "span3", size = "30"})
						@Html.ValidationMessageFor(p => p.Pname)
					</td>
				</tr>

				<tr>
					<td>
                        規格
					</td>
					<td>
						@Html.TextBoxFor(p => p.Spec, new { @class = "span5", size = "30"})
						@Html.ValidationMessageFor(p => p.Spec)
					</td>
				</tr>
				<tr>
					<td>
                        備註
					</td>
					<td>
						@Html.TextAreaFor(p => p.Summmary, new { @class = "span10" })
						@Html.ValidationMessageFor(p => p.Summmary)
					</td>
				</tr>

            </tbody>
        </table>
    </div>

	
    <div class="BTNcenter">
        <input type="submit" class="btn" id="btn_submit" name="btn_submit" value="儲存送出" onclick="javascript:return confirm('確定儲存送出嗎?');">
        <input type="button" class="btn" id="btn_cancle" name="btn_cancle" value="取消變更" onclick="javascript:if (confirm('確定取消變更嗎?')){window.location.href='@Url.Content("~/" + _Controller + "/List")';}">
    </div>